#!/bin/bash

echo -e "\n"

if [ -e src/index.md ]
then
  echo -e "removing src/index.md"
  rm src/index.md
  echo -e "removing src/index.md.html\n"
  rm src/index.md.html
fi

for document in $(find src ! -name 'src/index.md' -iname \*.md); do
  echo "generating markup for $document"

  `pandoc --from=markdown --to=html $document > $(echo $document | sed 's/.md/.md.html/')`

  while IFS= read -r line; do
    if [[ $line =~ ^#[[:space:]](.+) ]]; then
      echo -e "adding $document to table of contents\n"
      echo -e "[${BASH_REMATCH[1]}](`echo $document | sed 's/src\///' `?published=true)\n" >> src/index.md
    fi
  done < $document
done

echo -e "generating markup for index\n"
`pandoc --from=markdown --to=html 'src/index.md' --output='src/index.md.html'`

echo -e "done.\n\n"
