#!/bin/bash

echo -e "\n"

generateMarkup () {
  echo "generating markup for $1"
  `babel-node ejs-cli.js $1 > $(echo $1 | sed 's/.md/.md.html/' | sed 's/src\///')`
  return 0
}

if [ -n "$1" ]
then
  generateMarkup $1
  exit 0
fi

for document in $(find src ! -name 'index.md' -iname \*.md); do
  generateMarkup $document
done

echo "generating markup for src/index.md"
`babel-node ejs-cli.js src/index.md src/header.html src/footer.html | sed 's/\.md/\.md\.html/'  > index.html`

echo -e "\ndone.\n\n"
